# Generated by Django 3.1.5 on 2021-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='key',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
